select apellido1, apellido2, nombre from persona order by apellido1 asc, apellido2 asc, nombre asc;      
select nombre, apellido1, apellido2 from persona where tipo = 'alumno' and telefono is null;	
select * from persona where tipo = 'alumno' and year(fecha_nacimiento) = '1999';
select * from persona where tipo = 'profesor' and telefono is null and nif like '%k';
select * from universidad.asignatura where id and curso = 3 and cuatrimestre=1 and id_grado = 7;
select   per.apellido1, per.apellido2, per.nombre, dep.nombre from 	profesor prof join persona per on prof.id_profesor = per.id join departamento dep on prof.id_departamento = dep.id order by  per.apellido1 asc, per.apellido2 asc, per.nombre asc;       
select persona.nif, asignatura.nombre, curso_escolar.anyo_inicio, curso_escolar.anyo_fin from alumno_se_matricula_asignatura join persona on alumno_se_matricula_asignatura.id_alumno = persona.id join asignatura on alumno_se_matricula_asignatura.id_asignatura= asignatura.id join curso_escolar on alumno_se_matricula_asignatura.id_curso_escolar=curso_escolar.id where  persona.nif ='26902806M';
select   distinct dep.nombre  from profesor prof join departamento dep on prof.id_departamento = dep.id join asignatura asi on prof.id_profesor = asi.id_profesor join grado gra on asi.id_grado = gra.id where gra.nombre= 'Grado en Ingeniería Informática (Plan 2015)';
select distinct  persona.id, persona.nombre, curso_escolar.anyo_inicio from alumno_se_matricula_asignatura join persona on alumno_se_matricula_asignatura.id_alumno = persona.id join curso_escolar on alumno_se_matricula_asignatura.id_curso_escolar=curso_escolar.id where curso_escolar.anyo_inicio = '2018'; 
select dep.nombre as nombre_departamento, per.apellido1, per.apellido2, per.nombre from profesor pro left join persona per on pro.id_profesor = per.id left join departamento dep on pro.id_departamento = dep.id;
select prof.id_profesor from profesor prof left join departamento dep on prof.id_departamento = dep.id where prof.id_departamento is null;
select distinct dep.nombre from profesor prof right join departamento dep on prof.id_departamento = dep.id where prof.id_departamento is null;
select per.nombre, prof.id_profesor from profesor prof left join persona per on prof.id_profesor = per.id left join asignatura asi  on prof.id_profesor = asi.id_profesor	where asi.id_profesor is null;
select asi.* from asignatura asi left join profesor prof on asi.id_profesor = prof.id_profesor where asi.id_profesor is null;
select  dep.* from profesor prof right join departamento dep on prof.id_departamento = dep.id left  join asignatura asi on prof.id_profesor = asi.id_profesor where asi.id_profesor is null group by dep.id;
select count(*) as cantidad_alumnos from persona  where tipo = 'alumno';
select count(*) as cantidad_alumnos from persona  where tipo = 'alumno' and year(fecha_nacimiento) = '1999';
select dep.nombre as departamento, count(prof.id_profesor) as cantidad_profesores from profesor prof inner join departamento dep on prof.id_departamento = dep.id group by dep.id order by count(prof.id_profesor) desc;
select dep.nombre as 'departamento', count(prof.id_profesor) as 'num profesores' from profesor prof right join departamento dep on prof.id_departamento = dep.id group by dep.nombre;
select gra.*, count(asi.id) as 'asignatura' from grado gra left join asignatura asi on gra.id = asi.id_grado group by gra.id ORDER BY COUNT(asi.id) DESC;
select gra.*, count(asi.id) as 'asignatura' from grado gra join asignatura asi ON gra.id = asi.id_grado group by gra.id having count(asi.id) > '40';
select gra.nombre, asi.tipo, sum(asi.creditos) as 'total créditos' from grado gra right join asignatura asi on gra.id = asi.id_grado group by gra.nombre, asi.tipo;
select ce.anyo_inicio, count(asma.id_alumno) as 'total alumnos' from alumno_se_matricula_asignatura asma right join curso_escolar ce on asma.id_curso_escolar = ce.id group by ce.id;
select per.id, per.nombre, per.apellido1, per.apellido2, count(asi.id_profesor) as 'numero de asignaturas' from asignatura asi right join persona per on asi.id_profesor = per.id where per.tipo = 'profesor' group by per.id order by count(asi.id_profesor) desc;
select * from persona where   tipo = 'alumno' and fecha_nacimiento = (select max(fecha_nacimiento) from persona);
select  prof.id_profesor, per.nombre, per.apellido1 from profesor prof inner join persona per on prof.id_profesor = per.id left join asignatura asi on prof.id_profesor = asi.id_profesor where asi.id_profesor is null;
